"""initial schema

Revision ID: 7515715ae15b
Revises:
Create Date: 2026-04-27 09:13:33.889013+00:00

Creates every domain table (users, sellers, seller_documents, products,
orders, order_items, deliveries, payments) and the nine native PostgreSQL
ENUM types they reference.

NOTE on enums: SQLAlchemy auto-creates an enum type the first time it sees
``sa.Enum(..., name='foo')`` inside a ``CREATE TABLE``. ``DROP TABLE`` does
**not** auto-drop those types, however, so without explicit ``DROP TYPE``
calls in ``downgrade()`` a subsequent re-upgrade fails with
"type X already exists". The downgrade below drops every enum after the
tables are gone to keep migrations cleanly round-trippable.
"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7515715ae15b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# All enum type names this migration introduces. Listed once so upgrade() and
# downgrade() can stay in sync without hand-editing two places.
ENUM_TYPES: tuple[str, ...] = (
    "user_role",
    "seller_approval_status",
    "seller_document_type",
    "seller_document_status",
    "order_status",
    "delivery_carrier",
    "delivery_status",
    "payment_gateway",
    "payment_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('BUYER', 'SELLER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('sellers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_registration_number', sa.String(length=64), nullable=False),
    sa.Column('business_address', sa.Text(), nullable=False),
    sa.Column('bank_account_number', sa.String(length=64), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='seller_approval_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_sellers_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sellers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sellers')),
    sa.UniqueConstraint('business_registration_number', name=op.f('uq_sellers_business_registration_number')),
    sa.UniqueConstraint('user_id', name=op.f('uq_sellers_user_id'))
    )
    op.create_index(op.f('ix_sellers_approval_status'), 'sellers', ['approval_status'], unique=False)
    op.create_table('orders',
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('total_amount_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount_krw', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='order_status'), nullable=False),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('payment_reference', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_orders_buyer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_orders_seller_id_sellers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('ix_orders_buyer_status', 'orders', ['buyer_id', 'status'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_seller_status', 'orders', ['seller_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_krw', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('price_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('image_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_krw >= 0', name=op.f('ck_products_price_krw_non_negative')),
    sa.CheckConstraint('price_uzs >= 0', name=op.f('ck_products_price_uzs_non_negative')),
    sa.CheckConstraint('stock_quantity >= 0', name=op.f('ck_products_stock_non_negative')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_products_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_products_seller_id_sellers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index('ix_products_listing', 'products', ['is_approved', 'is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.create_table('seller_documents',
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('BUSINESS_REGISTRATION', 'BANK_VERIFICATION', 'EXPORT_LICENSE', name='seller_document_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_UPLOAD', 'UPLOADED', name='seller_document_status'), nullable=False),
    sa.Column('file_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_seller_documents_seller_id_sellers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seller_documents'))
    )
    op.create_index(op.f('ix_seller_documents_seller_id'), 'seller_documents', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_documents_status'), 'seller_documents', ['status'], unique=False)
    op.create_table('deliveries',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('tracking_number', sa.String(length=120), nullable=False),
    sa.Column('carrier', sa.Enum('CJ_LOGISTICS', 'KOREA_POST', 'DHL', name='delivery_carrier'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'EXCEPTION', name='delivery_status'), nullable=False),
    sa.Column('estimated_delivery_date', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_deliveries_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('order_id', name=op.f('uq_deliveries_order_id'))
    )
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_deliveries_tracking_number'), 'deliveries', ['tracking_number'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unit_price_krw', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.CheckConstraint('unit_price_krw >= 0', name=op.f('ck_order_items_unit_price_krw_non_negative')),
    sa.CheckConstraint('unit_price_uzs >= 0', name=op.f('ck_order_items_unit_price_uzs_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('gateway', sa.Enum('TOSS', 'KG_INICIS', 'PAYME', 'CLICK', 'UZCARD', name='payment_gateway'), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('amount_uzs', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_krw', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('exchange_rate_used', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_gateway_transaction_id'), 'payments', ['gateway_transaction_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_transaction_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_deliveries_tracking_number'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_seller_documents_status'), table_name='seller_documents')
    op.drop_index(op.f('ix_seller_documents_seller_id'), table_name='seller_documents')
    op.drop_table('seller_documents')
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_index('ix_products_listing', table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('ix_orders_seller_status', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_buyer_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_sellers_approval_status'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Drop enum types last — see header note for rationale.
    bind = op.get_bind()
    for enum_name in ENUM_TYPES:
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
